force-app/main/default/objects/Parking_Loaction__c/Parking_Loaction__c.object-meta.xml
<CustomObject>
    <label>Parking Loaction</label>
    <nameField>
        <label>Parking Loaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parking Loactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Parking_Loaction__c/fields/Landmark__c.field-meta.xml
<CustomField>
    <fullName>Landmark__c</fullName>
    <label>Landmark</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Time_Slot__c/Time_Slot__c.object-meta.xml
<CustomObject>
    <label>Time Slot</label>
    <nameField>
        <label>Time Slot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time Slots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ParkingSpaceControllerTest.cls
@isTest
public class ParkingSpaceControllerTest {   
@isTest
 public static void getParkingLoactionTest(){
    String cities = 'Bangalore';
    String place = 'koramangala';
    Parking_Loaction__c plocation = new Parking_Loaction__c();
        plocation.Name = 'Testlocation';
        plocation.City__c = cities;
        plocation.Landmark__c = place;
        insert plocation;
    List<Parking_Loaction__c> parkinglocation = ParkingSpaceController.getParkingLoaction(cities,place);
    System.assertEquals(parkinglocation.size(),1);
 }

  
 @isTest
 public static void getTimeSlotTest(){
     date myDate = date.newInstance(2023, 12, 10);
    String selectedDate =String.valueOf(myDate);
    String timeSlot = '1PM to 2PM';
    Time_Slot__c tslot = new Time_Slot__c();
    tslot.Name = 'test';
    insert tslot;
    List<Time_Slot__c> bookedSlot = ParkingSpaceController.getTimeSlot(tslot.Id,selectedDate,timeSlot);
  
 }

 @isTest
 public static void bookSlotsTest(){
    String id = 'f123';
    String email = 'test@gmail.com';
    String numval = '12346';
    String name = 'test';
    Time_Slot__c slotbook = new Time_Slot__c();
    slotbook.Name = name;
    insert slotbook;
    
   
    ParkingSpaceController.bookSlots(slotbook.Id,email,numval,name);
   
 }
}